Repository Promise-of-Blood/SeeAt, pull requests merged in 2024-10, with the labels that each got.

#232 위치 권한 두 번째 요청 시 허용 여부에 관계 없이 거부했다는 토스트 메시지가 나오는 현상 해결
  app/src/main/java/com/pob/seeat/presentation/view/PermissionGuideActivity.kt
  app/src/main/java/com/pob/seeat/utils/PermissionSupport.kt
Labels: 🔧 Fix

#233 사용자 활동이 일부만 표시되는 현상 해결
  app/src/main/java/com/pob/seeat/presentation/view/mypage/history/HistoryFragment.kt
  app/src/main/res/layout/fragment_history.xml
Labels: 🔧 Fix

#238 firebase-crashlytics SDK, 플러그인 추가
  app/build.gradle.kts
  build.gradle.kts
  gradle/libs.versions.toml
Labels: ✨ Feature, ⚙️ Chore

#239 Fix detail refresh
  app/src/main/java/com/pob/seeat/presentation/view/detail/DetailFragment.kt
  app/src/main/java/com/pob/seeat/presentation/view/detail/EditDetailFragment.kt
  app/src/main/java/com/pob/seeat/presentation/view/feed/NewFeedFragment.kt
  app/src/main/java/com/pob/seeat/presentation/view/home/HomeFragment.kt
  app/src/main/java/com/pob/seeat/presentation/view/mypage/EditProfileActivity.kt
  app/src/main/java/com/pob/seeat/presentation/view/mypage/MyPageFragment.kt
  app/src/main/java/com/pob/seeat/presentation/view/sign/LoginActivity.kt
  app/src/main/java/com/pob/seeat/presentation/view/sign/SignUpPhotoFragment.kt
  app/src/main/java/com/pob/seeat/presentation/viewmodel/DetailViewModel.kt
  app/src/main/java/com/pob/seeat/utils/EventBus.kt
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_edit_detail.xml
Labels: 🐛 Bug, 🔧 Fix
