Repository Promise-of-Blood/SeeAt, pull requests merged in 2024-09, with the labels that each got.

#138 Feature add marker
  app/src/main/java/com/pob/seeat/presentation/view/feed/NewFeedFragment.kt
  app/src/main/java/com/pob/seeat/utils/Utils.kt
  app/src/main/res/layout/item_image_upload.xml
Labels: bug

#146 Feature 게시글 신고 및 삭제 구현
  app/src/main/java/com/pob/seeat/data/remote/DetailFeed.kt
  app/src/main/java/com/pob/seeat/data/remote/FeedRemote.kt
  app/src/main/java/com/pob/seeat/data/remote/ReportFeedRemote.kt
  app/src/main/java/com/pob/seeat/data/remote/SendReportFeed.kt
  app/src/main/java/com/pob/seeat/data/repository/FeedRepositoryImpl.kt
  app/src/main/java/com/pob/seeat/data/repository/ReportFeedRepositoryImpl.kt
  app/src/main/java/com/pob/seeat/di/ReportFeedModule.kt
  app/src/main/java/com/pob/seeat/domain/model/FeedReportModel.kt
  app/src/main/java/com/pob/seeat/domain/repository/FeedRepository.kt
  app/src/main/java/com/pob/seeat/domain/repository/ReportFeedRepository.kt
  app/src/main/java/com/pob/seeat/domain/usecase/RemoveFeedUseCase.kt
  app/src/main/java/com/pob/seeat/domain/usecase/ReportFeedUseCase.kt
  app/src/main/java/com/pob/seeat/presentation/view/detail/DetailFragment.kt
  app/src/main/java/com/pob/seeat/presentation/viewmodel/DetailViewModel.kt
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/menu/menu_detail.xml
  app/src/main/res/menu/menu_detail_another_user.xml
  app/src/main/res/values/strings.xml
Labels: Feature

#171 Add back on detail
  app/src/main/java/com/pob/seeat/MainActivity.kt
  app/src/main/java/com/pob/seeat/domain/repository/FeedRepository.kt
  app/src/main/java/com/pob/seeat/presentation/view/detail/DetailFragment.kt
  app/src/main/java/com/pob/seeat/presentation/view/home/EmptyFragment.kt
  app/src/main/java/com/pob/seeat/presentation/view/home/HomeFragment.kt
  app/src/main/java/com/pob/seeat/presentation/viewmodel/HomeViewModel.kt
  app/src/main/java/com/pob/seeat/utils/Utils.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_empty.xml
  app/src/main/res/navigation/main_navigation.xml
Labels: Add

#177 Refactor add marker
  app/src/main/java/com/pob/seeat/MainActivity.kt
  app/src/main/java/com/pob/seeat/presentation/view/feed/NewFeedFragment.kt
  app/src/main/java/com/pob/seeat/presentation/view/feed/OnLocationSelectedListener.kt
  app/src/main/java/com/pob/seeat/presentation/view/feed/SelectLocateFragment.kt
  app/src/main/java/com/pob/seeat/presentation/view/home/HomeFragment.kt
  app/src/main/res/drawable/background_edit_text.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_new_feed.xml
  app/src/main/res/layout/fragment_select_locate.xml
  app/src/main/res/navigation/main_navigation.xml
Labels: Add

#178 Refactor add marker
  app/src/main/java/com/pob/seeat/presentation/view/chat/ChattingActivity.kt
  app/src/main/java/com/pob/seeat/presentation/view/chat/ChattingFragment.kt
  app/src/main/java/com/pob/seeat/presentation/view/feed/NewFeedFragment.kt
  app/src/main/res/layout/fragment_select_locate.xml
Labels: bug

#179 Refactor home marker
  app/src/main/java/com/pob/seeat/presentation/view/feed/NewFeedFragment.kt
  app/src/main/java/com/pob/seeat/presentation/view/home/HomeFragment.kt
  app/src/main/res/drawable/ic_growing_seed.xml
  app/src/main/res/drawable/ic_growing_sprout.xml
  app/src/main/res/drawable/ic_seed.xml
  app/src/main/res/drawable/ic_sprout.xml
  app/src/main/res/drawable/ic_tree.xml
Labels: Add

#189 Feature detail edit
  app/src/main/java/com/pob/seeat/data/remote/DetailFeed.kt
  app/src/main/java/com/pob/seeat/data/remote/FeedRemote.kt
  app/src/main/java/com/pob/seeat/data/repository/FeedRepositoryImpl.kt
  app/src/main/java/com/pob/seeat/di/UseCaseModule.kt
  app/src/main/java/com/pob/seeat/domain/repository/FeedRepository.kt
  app/src/main/java/com/pob/seeat/domain/usecase/EditFeedUseCase.kt
  app/src/main/java/com/pob/seeat/presentation/view/detail/DetailFragment.kt
  app/src/main/java/com/pob/seeat/presentation/view/detail/EditDetailFragment.kt
  app/src/main/java/com/pob/seeat/presentation/view/feed/NewFeedFragment.kt
  app/src/main/java/com/pob/seeat/presentation/view/feed/SelectLocateFragment.kt
  app/src/main/java/com/pob/seeat/presentation/viewmodel/DetailViewModel.kt
  app/src/main/res/layout/fragment_edit_detail.xml
  app/src/main/res/menu/menu_detail.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values/strings.xml
Labels: Feature

#196 BugFix: 좋아요 숫자 버그 수정 #191
  app/src/main/java/com/pob/seeat/presentation/view/detail/DetailFragment.kt
  app/src/main/java/com/pob/seeat/presentation/viewmodel/DetailViewModel.kt
  app/src/main/res/layout/fragment_detail.xml
Labels: bug

#201 Add user distance
  app/src/main/java/com/pob/seeat/data/remote/DetailFeed.kt
  app/src/main/java/com/pob/seeat/data/remote/FeedRemote.kt
  app/src/main/java/com/pob/seeat/data/remote/GetFeedList.kt
  app/src/main/java/com/pob/seeat/data/repository/FeedRepositoryImpl.kt
  app/src/main/java/com/pob/seeat/domain/model/FeedModel.kt
  app/src/main/java/com/pob/seeat/domain/repository/FeedRepository.kt
  app/src/main/java/com/pob/seeat/presentation/view/chat/ChattingFragment.kt
  app/src/main/java/com/pob/seeat/presentation/view/detail/DetailFragment.kt
  app/src/main/java/com/pob/seeat/presentation/view/feed/NewFeedFragment.kt
  app/src/main/java/com/pob/seeat/presentation/view/home/HomeFragment.kt
  app/src/main/java/com/pob/seeat/presentation/view/home/adapter/BottomSheetFeedAdapter.kt
  app/src/main/java/com/pob/seeat/presentation/view/home/adapter/TagAdapter.kt
  app/src/main/java/com/pob/seeat/presentation/viewmodel/DetailViewModel.kt
  app/src/main/java/com/pob/seeat/presentation/viewmodel/HomeViewModel.kt
  app/src/main/java/com/pob/seeat/utils/GetUserLocation.kt
  app/src/main/java/com/pob/seeat/utils/Utils.kt
  app/src/main/res/drawable/ic_growing_seed.png
  app/src/main/res/drawable/ic_growing_seed.xml
  app/src/main/res/drawable/ic_growing_sprout.png
  app/src/main/res/drawable/ic_growing_sprout.xml
  app/src/main/res/drawable/ic_seed.png
  app/src/main/res/drawable/ic_seed.xml
  app/src/main/res/drawable/ic_sprout.png
  app/src/main/res/drawable/ic_sprout.xml
  app/src/main/res/drawable/ic_tree.png
  app/src/main/res/drawable/ic_tree.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_new_feed.xml
  app/src/main/res/layout/post_item.xml
  app/src/main/res/values/colors.xml
Labels: Add

#222 Refactor 게시글 목록 디자인 개선
  app/src/main/java/com/pob/seeat/presentation/view/home/adapter/BottomSheetFeedAdapter.kt
  app/src/main/res/layout/post_item.xml
Labels: Refactor
